Resources:
  PhotosTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: Arrow
      AttributeDefinitions:
        - AttributeName: "messageId"
          AttributeType: "S"
      KeySchema:
        - AttributeName: "messageId"
          KeyType: "HASH"
      BillingMode: "PAY_PER_REQUEST"